# Generated by Django 5.2 on 2025-11-12 23:12

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=usuarios.models.avatar_upload_path)),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje de bienvenida')),
                ('idioma', models.CharField(default='Español', max_length=20)),
                ('hora', models.CharField(default='24h', max_length=20)),
                ('pais', models.CharField(default='Colombia', max_length=50)),
                ('zona', models.CharField(default='UTC -5 Bogotá', max_length=50)),
                ('genero', models.CharField(blank=True, default='Otro', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
